spring.application.name=havenstay
server.port = 9090

# MySQL
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

# Hibernate
spring.jpa.hibernate.ddl-auto=update

#Jwt
secreteJwtString=mine9479347secret3r0324023long3u924key3

#mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=havenstay.reservations@gmail.com
spring.mail.password=wbfa mrgx bgqu coyr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true